name: JBossWS-CXF CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['8', '11']
        wildfly-version: ['wildfly2400','wildfly2400picketbox','wildfly2400nolegacy' ]

    steps:
      - name: Checkout jbossws-cxf
        uses: actions/checkout@v2
      - name: Checkout jbossws-wildfly240
        uses: actions/checkout@v2
        with:
          repository: jbossws/jbossws-wildfly240
          path: './jbossws-wildfly240'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build  jbossws-wildfly240
        working-directory: ./jbossws-wildfly240
        run: mvn -s ./.m2-settings.xml -DskipTests=true clean install
      - name: Build with Maven Java ${{ matrix.java }} on WildFly ${{ matrix.wildfly-version }}
        run: |
          mvn -s ./.m2-settings.xml -B -V -fae -P${{ matrix.wildfly-version }} -Pdeploy verify
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}-picketbox-elytron
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}-picketbox-elytron
          path: '**/server.log'