name: JBossWS-CXF CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['17']
        wildfly-version: ['wildfly2700']

    steps:
      - name: Checkout jbossws-cxf
        uses: actions/checkout@v2
      - name: Checkout cxf xjcutils
        uses: actions/checkout@v2
        with:
          repository: apache/cxf-xjc-utils
          ref: master
          path: './cxf-xjc-utils'
      - name: Checkout cxf
        uses: actions/checkout@v2
        with:
          repository: apache/cxf
          ref: CXF-8371
          path: './cxf'
      - name: Checkout wildfly
        uses: actions/checkout@v2
        with:
          repository: jimma/wildfly
          ref: cxf-jakarta
          path: './wildfly'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build CXF xjc utils
        working-directory: ./cxf-xjc-utils
        run: mvn clean install -Pfastinstall
      - name: Build CXF tools common
        working-directory: ./cxf/tools/common
        run: mvn clean install
      - name: Build CXF
        working-directory: ./cxf
        run: mvn clean install -Pfastinstall
      - name: Build WFLY
        working-directory: ./wildfly
        run: mvn -s ../.m2-settings.xml -DskipTests=true '-Denforcer.skip=true' -Prelease clean install
      - name: Build with Maven Java ${{ matrix.java }} on WildFly ${{ matrix.wildfly-version }}
        run: |
          mvn -s ./.m2-settings.xml -B -V -fae -P${{ matrix.wildfly-version }} verify
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/server.log'